spring:
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      database: walletdb
      username: admin
      password: admin
      host: localhost
      port: 27017
      authentication-database: admin
---
spring:
  config:
    activate:
      on-profile: test
  mongodb:
    embedded:
      version: 4.4.9
